modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "vmmod"
version = "1.0.0"
displayName = "VanillaMinigames Mod"
displayURL = "https://vanillaminigames.eu/"
logoFile = "logo.png"
credits = "Thanks to thevalleyy for this great textures"
authors = ["Benonardo", "booky10"]
description = 'A mod with insiders from the VanillaMinigames.eu Minecraft Server.'

[[dependencies.vmmod]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vmmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
